services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port for viewing browser (optional)
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300

  scraper:
    build: .
    depends_on:
      - selenium-chrome
    volumes:
      - .:/workspace
    environment:
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    ports:
      - "8000:8000"